// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hewfqryvvczqdsnsqzxs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhld2Zxcnl2dmN6cWRzbnNxenhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgwMTcwNzksImV4cCI6MjA1MzU5MzA3OX0.C374wogesV3ctjmASXcqvh3pnWrVynQsm6G8tnsE3MI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);